name: Deploy to Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check AWS CLI version
      run: aws --version

    - name: Configure AWS CLI
      run: |
        aws configure set region ${{ secrets.AWS_REGION }} 
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Set up SSH for EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EB_SSH }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa 172.31.17.167 >> ~/.ssh/known_hosts

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        APPLICATION_NAME: 'royal-fluff-backend'
        ENVIRONMENT_NAME: 'Royal-fluff-backend-env-1'
      run: |
        # Initialize Elastic Beanstalk (non-interactive)
        eb init $APPLICATION_NAME \
          --region $AWS_REGION \
          --platform "Python" \
          --no-verify-ssl  
        eb use $ENVIRONMENT_NAME
        eb deploy

    - name: Run Migrations
      run: |
        eb ssh $ENVIRONMENT_NAME --command "source /var/app/venv/*/bin/activate && python /var/app/current/manage.py migrate"

    - name: Set Environment Variables in Beanstalk
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        eb setenv DJANGO_ENV=production \
                  DB_HOST="$DB_HOST" \
                  DB_NAME="$DB_NAME" \
                  DB_USERNAME="$DB_USERNAME" \
                  DB_PASSWORD="$DB_PASSWORD" \
                  DJANGO_SECRET_KEY="$DJANGO_SECRET_KEY"